export const nameList = [
    'Time', 'Past', 'Future', 'Dev',
    'Fly', 'Flying', 'Soar', 'Soaring', 'Power', 'Falling',
    'Fall', 'Jump', 'Cliff', 'Mountain', 'Rend', 'Red', 'Blue',
    'Green', 'Yellow', 'Gold', 'Demon', 'Demonic', 'Panda', 'Cat',
    'Kitty', 'Kitten', 'Zero', 'Memory', 'Trooper', 'XX', 'Bandit',
    'Fear', 'Light', 'Glow', 'Tread', 'Deep', 'Deeper', 'Deepest',
    'Mine', 'Your', 'Worst', 'Enemy', 'Hostile', 'Force', 'Video',
    'Game', 'Donkey', 'Mule', 'Colt', 'Cult', 'Cultist', 'Magnum',
    'Gun', 'Assault', 'Recon', 'Trap', 'Trapper', 'Redeem', 'Code',
    'Script', 'Writer', 'Near', 'Close', 'Open', 'Cube', 'Circle',
    'Geo', 'Genome', 'Germ', 'Spaz', 'Shot', 'Echo', 'Beta', 'Alpha',
    'Gamma', 'Omega', 'Seal', 'Squid', 'Money', 'Cash', 'Lord', 'King',
    'Duke', 'Rest', 'Fire', 'Flame', 'Morrow', 'Break', 'Breaker', 'Numb',
    'Ice', 'Cold', 'Rotten', 'Sick', 'Sickly', 'Janitor', 'Camel', 'Rooster',
    'Sand', 'Desert', 'Dessert', 'Hurdle', 'Racer', 'Eraser', 'Erase', 'Big',
    'Small', 'Short', 'Tall', 'Sith', 'Bounty', 'Hunter', 'Cracked', 'Broken',
    'Sad', 'Happy', 'Joy', 'Joyful', 'Crimson', 'Destiny', 'Deceit', 'Lies',
    'Lie', 'Honest', 'Destined', 'Bloxxer', 'Hawk', 'Eagle', 'Hawker', 'Walker',
    'Zombie', 'Sarge', 'Capt', 'Captain', 'Punch', 'One', 'Two', 'Uno', 'Slice',
    'Slash', 'Melt', 'Melted', 'Melting', 'Fell', 'Wolf', 'Hound',
    'Legacy', 'Sharp', 'Dead', 'Mew', 'Chuckle', 'Bubba', 'Bubble', 'Sandwich', 'Smasher', 'Extreme', 'Multi', 'Universe', 'Ultimate', 'Death', 'Ready', 'Monkey', 'Elevator', 'Wrench', 'Grease', 'Head', 'Theme', 'Grand', 'Cool', 'Kid', 'Boy', 'Girl', 'Vortex', 'Paradox'
  ];

  export const quotes = [
    "Make hay while the sun shines",
    "Sun rises in the east",
    "Actions speak louder than words",
    "A journey of a thousand miles begins with a single step",
    "Better late than never",
    "Practice makes perfect",
    "Honesty is the best policy",
    "A picture is worth a thousand words",
    "The pen is mightier than the sword",
    "When in Rome, do as the Romans do",
    "Necessity is the mother of invention",
    "Fortune favors the bold",
    "No pain, no gain",
    "Time and tide wait for no one",
    "Every cloud has a silver lining",
    "Where there's a will, there's a way",
    "You reap what you sow",
    "Rome wasn't built in a day",
    "Don't bite the hand that feeds you",
    "Two heads are better than one",
    "Beauty is in the eye of the beholder",
    "The early bird catches the worm",
    "Look before you leap",
    "A stitch in time saves nine",
    "Fools rush in where angels fear to tread",
    "Too many cooks spoil the broth",
    "A watched pot never boils",
    "Birds of a feather flock together",
    "Don't judge a book by its cover",
    "Actions speak louder than words",
    "Out of sight, out of mind",
    "A penny saved is a penny earned",
    "God helps those who help themselves",
    "The best things in life are free",
    "A fool and his money are soon parted",
    "Absence makes the heart grow fonder",
    "Blood is thicker than water",
    "Cleanliness is next to godliness",
    "Discretion is the better part of valor",
    "Don't count your chickens before they hatch",
    "Don't put all your eggs in one basket",
    "Easier said than done",
    "Good things come to those who wait",
    "Haste makes waste",
    "If it ain't broke, don't fix it",
    "If you can't beat them, join them",
    "It takes two to tango",
    "Laughter is the best medicine",
    "Let sleeping dogs lie",
    "Lightning never strikes twice in the same place",
    "Money doesn't grow on trees",
    "Necessity is the mother of invention",
    "Old habits die hard",
    "One man's trash is another man's treasure"]
